/**
 * Generates dist/sw.js after a Vite build.
 *
 * The service worker precaches every file emitted into dist/, which is what makes the app keep
 * working after the server goes away: load it once, then use it forever, fully offline.
 *
 * Entries are cached one by one rather than with `cache.addAll`, which is atomic: a single
 * unreadable asset would abort the whole install and leave the page with no worker at all.
 * Progress is broadcast to open pages so a slow precache can show a percentage.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, posix, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const distDir = fileURLToPath(new URL('../dist', import.meta.url));

const walk = async (dir) => {
	const found = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) {
			found.push(...(await walk(full)));
		} else if (entry.isFile()) {
			found.push(full);
		}
	}
	return found;
};

const main = async () => {
	await stat(distDir).catch(() => {
		throw new Error('dist/ not found - run "vite build" first.');
	});

	const files = (await walk(distDir)).filter((file) => !file.endsWith(`${sep}sw.js`));
	const hash = createHash('sha256');
	const assets = [];

	for (const file of files.sort()) {
		const url = `./${relative(distDir, file).split(sep).join(posix.sep)}`;
		assets.push(url);
		hash.update(url);
		hash.update(await readFile(file));
	}

	const version = hash.digest('hex').slice(0, 12);
	const precache = ['./', ...assets];

	const source = `// Generated by scripts/build-sw.mjs - do not edit by hand.
const VERSION = '${version}';
const CACHE_PREFIX = 'auto-video-fusion-';
const CACHE_NAME = CACHE_PREFIX + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, '\t')};
// Enough parallelism to keep the connection busy without starving the network on a
// slow NAS link, where a serial precache would look like it had hung.
const CONCURRENCY = 6;

// Snapshot of precache progress so a page that loads mid-install can ask for the
// current state instead of waiting for the next broadcast.
let status = {
	type: 'precache-progress',
	version: VERSION,
	state: 'idle',
	done: 0,
	total: PRECACHE.length,
	failed: [],
};

const broadcast = async () => {
	const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
	for (const client of clients) client.postMessage(status);
};

const precacheAll = async () => {
	const cache = await caches.open(CACHE_NAME);
	status = { ...status, state: 'caching', done: 0, failed: [] };
	await broadcast();

	const queue = PRECACHE.slice();
	const failed = [];
	let done = 0;

	const drain = async () => {
		for (;;) {
			const url = queue.shift();
			if (url === undefined) return;
			try {
				// 'reload' bypasses the HTTP cache so a precache always stores fresh bytes.
				const response = await fetch(new Request(url, { cache: 'reload' }));
				if (!response.ok) throw new Error('HTTP ' + response.status);
				await cache.put(url, response);
			} catch {
				// Individual failures must not abort the install the way cache.addAll would:
				// one unreadable asset would otherwise leave the app with no worker at all.
				failed.push(url);
			}
			done += 1;
			status = { ...status, done, failed: failed.slice() };
			await broadcast();
		}
	};

	await Promise.all(Array.from({ length: Math.min(CONCURRENCY, queue.length) }, drain));

	status = { ...status, state: failed.length ? 'incomplete' : 'ready', done, failed: failed.slice() };
	await broadcast();
};

self.addEventListener('install', (event) => {
	event.waitUntil(precacheAll().then(() => self.skipWaiting()));
});

self.addEventListener('message', (event) => {
	const data = event.data;
	if (!data || data.type !== 'precache-status') return;
	const port = event.ports && event.ports[0];
	if (port) port.postMessage(status);
	else if (event.source) event.source.postMessage(status);
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches
			.keys()
			.then((keys) =>
				Promise.all(
					keys
						.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
						.map((key) => caches.delete(key)),
				),
			)
			.then(() => self.clients.claim()),
	);
});

self.addEventListener('fetch', (event) => {
	const request = event.request;
	if (request.method !== 'GET') return;

	const url = new URL(request.url);
	if (url.origin !== self.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);
			// \`ignoreVary\` is essential: precached entries are fetched by this worker, while the page
			// requests the same files in CORS mode. Servers that send \`Vary: Origin\` would otherwise
			// make every precached asset unreachable offline.
			const lookup = (req) => cache.match(req, { ignoreVary: true });

			if (request.mode === 'navigate') {
				try {
					const fresh = await fetch(request);
					cache.put(request, fresh.clone());
					return fresh;
				} catch {
					return (
						(await lookup(request)) ||
						(await lookup('./index.html')) ||
						(await lookup('./')) ||
						Response.error()
					);
				}
			}

			const cached = await lookup(request);
			if (cached) return cached;

			try {
				const fresh = await fetch(request);
				if (fresh.ok && fresh.type === 'basic') cache.put(request, fresh.clone());
				return fresh;
			} catch {
				return (await cache.match(request, { ignoreVary: true, ignoreSearch: true })) || Response.error();
			}
		})(),
	);
});
`;

	await writeFile(join(distDir, 'sw.js'), source, 'utf8');
	console.log(`Service worker written (version ${version}, ${precache.length} precached entries).`);
};

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
